# fly.toml app configuration file generated for backend-teachers-syndicate on 2025-08-29T22:02:37Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'backend-teachers-syndicate'
primary_region = 'cdg'

[build]

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
